### ISSUE TITLE
No authorization header in the request

### ISSUE THREAD

**Issue by evansmwenda** [catalyst/moodle-webservice_restful#10]
Im using Moodle version 3.7.6 and somehow the plugin doesnt detect the authorization header that i have sent. Here is how i sent it:
curl -X GET \
-H "Content-Type: application/json" \
-H "Accept: application/json" \
-H 'Authorization: my-token' \
"http:/my-moodle-site/moodle/webservice/restful/server.php/auth_email_get_signup_settings"

Any help will be appreciated

**Comment by wgap42** [comment]
Take a look at [this posting on github](https://github.com/catalyst/moodle-webservice_restful/issues/11)

It seems that the link on the moodle site is to an earlier version of the restful plugin.
I had the same issue.

Getting the latest master from github and installing that, the issue is no longer occurring

**Comment by mattporritt** [comment]
Answered here: https://github.com/catalyst/moodle-webservice_restful/issues/10#issuecomment-747695891
